# Change these first
owner: tuskeNetwork # Your GitHub organization or username, where this repository lives
repo: tuskeUptime # The name of this repository

sites:
  - name: Website
    url: https://tuske.network
  - name: Explorer
    url: https://explorer.tuske.network
  - name: Seednode-USA
    url: us.tuske.network
    port: 20240
    check: "tcp-ping"
  - name: Seednode-German
    url: de.tuske.network
    port: 20240
    check: "tcp-ping"
  - name: Seednode-Singapore
    url: sg.tuske.network
    port: 20240
    check: "tcp-ping"  
  - name: Seednode-Australia
    url: au.tuske.network
    port: 20240
    check: "tcp-ping"  
  - name: Seednode-India
    url: in.tuske.network
    port: 20240
    check: "tcp-ping"  
  - name: PublicNode-USA
    url: node-us.tuske.network
    port: 20240
    check: "tcp-ping"  
  - name: PublicNode-Japan
    url: node-jp.tuske.network
    port: 20240
    check: "tcp-ping"      

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.tuske.network
  # baseUrl: /your-repo-name
  logoUrl: https://tuske.network/logo.png
  name: Tuske Service Status
  introTitle: "Tuske Service Status"
  introMessage: Service status is updated approximately every 5-30 minutes. Charts are updated less frequently.
  theme: light
  navbar:
    - title: Twitter
      href: https://x.com/tuske_Network
    - title: Discord
      href: https://discord.com/invite/JZrzM6q43V

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
